dist: bionic

script:
  - bash build.sh

after_success:
  - id
  - sudo apt update
  - sudo apt install -y python3 python3-pip python3-dev python3-wheel python3-setuptools
  - pip3 install --user pipenv
  - cd $TRAVIS_BUILD_DIR/_util
  - pipenv sync
  - pipenv run python3 merge.py


notifications:
  slack:
    secure: "vV3KnfnppVwNpK5+X6ORDHIRVmohLpzx8kVyoCGj49QAltJaZITWUGFrrFwpECVTujmWFmkmYDail3gXrgbSZ2qpW8+luM6Pf/PwgDoGp84UTETwewcrOoZdChW4J86feRKn3bhuQJATuzrtsQDUoxqU66lFBqHYby4ZMJNNV/YCICVuSfpk1f04myH/oqjDA7T2nzA/TNDd/pf6TjufAXBLfspcYlF4ZujvgWIi/jQZptHEkPjX7SFrKPBJQPmmfMvXNGGE+KU3vOfmnQR/Z3FWVdjuwfcuBLIvBnAn1caTJm3fc3UlegNOje6cC+1GGgvt+FelblRiMqslCYt14MfwN2jolS1BxHAKWfeRjvbj4NPxA91IwbcQdEIIsdfTMCy4xI5POW7em1CsAiswS+pKQaFpP0ZKcbN4bjiSmbpF6CCRTnRT2kCWCCZb3wAPZCVzQWo07nOPvIJ9AvJZ5Pnl9q7MqFDyTqYxdvQIn6eQbsv3VYISGi7SsifTb5pk2Xx1x+JrHhyDxUqklGVtFN0lFODvwqXWt0Jv+Fs1e8lEMb6QSA7liPlB9teOU07azxtmLeicEQxnEpHBX+a9wphc+mkLtHg8QaUy0acWQwrJ2fhQK57arkAUdpfR8Iu7ngkb/SHSbhLLVUPmAgshI+Ae6xSKilLOcIfl7xqVw+g="


env:
  global:
    # SLACK_TOKEN
    - secure: "sAKT2aXIGqFb5y3YSs6C2aB1SZbpF4maYcQjQOv60m9rmiRpbvrj5GmgRvhJi5okodXHnYx8M8OhMx9PAIey6dgKcpVyumvq8uuRmsM0hlC3tpxDdiia6b68tC1L+KhVqwPwMKSP87IwmC5bjlhWUW0oroyBXv/R40qyJLpwwUpmqlquelplRtU5QafR6gjhhb2LYliz7b3bg1qujvflId/oKO3+51/aS8fcIxK5JlWDUcmK0l25IFIil0kkjLczxqco8coePZ99MLSmLXhOgLGwvtJAct55zuBf/W8uVlQyk9zDuMAVcydA3p83j67wjzUrIHjk0iNVTcBskwj+UZg27qMBN1WZh/uJh0kYZTrCkqZL759zsslSv/wmMoNAeg1dRE5m2tV4X6H0TwJm78Evl5VmP6zsy6GORvWgBxc4fcYRUifuuj3Y1BBd3lU1GvQc1CVK/qjNZCvA3Mh9DrCQ8FXdx13FcpeRUJeT5dQY3MYeEWADIRg64tzKlbhwiN/zWh0s+A6T8Dt3DwS4MSuInOtH5THjrpty4hAnfGqZKM0jE6xwmDgpGWVbVU//CjL7WlWDmrmBcBWbSPtvwCq0XiJaax14R5tJQiuaaOgdndqIGkkL1fMAz3ZRlD2q/vMf8v5GyWBq66L2T/xPEetTuxWqEPuhwtJ61pMdjlE="

    # GITHUB_TOKEN
    - secure: "OIwN5c4gkQ9haKYNTJrwB85YWXyQ0t7JJhRr6EGh/1EaDk8o9Bi5ebWsPFLNKvw23px9+Vspzx4H0pLKCjqv/y4XenBs40Ah6ki69XaCmbP/hdjRsBhPE5JToEbY/3rN744rlrD2L6AAKfP7JGbbXTTdXqsg3D71PX/JDWjcZgvjRVY97erJQe/enxTzcNgjjYpA+uQ3JFTAh/7E9ihUpKSI15r5i70kwzCXSDrXb9ULFOtFUpv3qBIgShk2/3m8bvieHGSs1flf43eUSlmBJbUEeWiYf2Uqla4vnXMa9M8B+QVyBOhGcEjgiQe6OXKZ4GccxP5HfVcYq1fyGGWeAXH5Igh46PBwg4AO3WHuVl++E2WYK8FGIrn99Ql91GGDMd1GKf7VOfI90LNhXxTqPe+Yjx0YFgIW8M3WdB3DJvgfLf7BjirH2fepMVa+80064SqfivgLRSsXDcJXl51T78gvmLswwznGpujRHuo7iGl4QKd1Rlfb9leq2scrAUzpBxY1k86oPRGK/7qg+E1cn1bC2NfyV98YQjRhxTuE//2DmQuI9F8XmxXWOSd3qjKkgivlPo6uZpupDfzvVMf/Q/dO1onAR1RYSdSCgCRFDhu0tDGfqsytIi73IAhtAcs84Fvd06EWRbzu3mfieJFrpTjoU61vWR0/5OT2m4cKRPY="
