name: build_docker_image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: bash build.sh

    - name: docker login
      run: cat ${{ secrets.DOCKER_PASS }} | docker login --username logickee --password-stdin

    - name: push docker image
      run: docker push logickee/lichee-nano:latest

  slack-notifications:
    runs-on: ubuntu-latest
    name: Sends a message to Slack when a push, a pull request or an issue is made
    steps:
      - name: Send message to Slack API
        uses: archive/github-actions-slack@master
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: build_result
          slack-text: |
            ${{ github.repository }} build done
            https://github.com/louiscklaw/lichee-nano/commit/$GITHUB_SHA/checks
